// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

// Only create client if credentials are available
const getSupabaseClient = () => {
  if (SUPABASE_URL === 'https://placeholder.supabase.co' || !SUPABASE_PUBLISHABLE_KEY) {
    console.warn('Supabase credentials not configured. RSVP functionality will not work.');
    return null;
  }
  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
};

export const supabase = getSupabaseClient();